name: class-test
on:
  push:
    branches:
      - master
jobs:
    Hello-User:
      runs-on: ubuntu-latest
      steps:
        - name: Check out repository code
          uses: actions/checkout@v2
        - name: Hello User